<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="b120871-lt" ignored="0" name="Default test" tests="5" failures="1" timestamp="24 Oct 2018 09:54:22 GMT" time="104.367" errors="0">
  <testcase name="TC01_MessageLogout" time="0.128" classname="WSM_LOGOUT.wsmLogout"/>
  <testcase name="TC02_LoginScreen" time="0.022" classname="WSM_LOGOUT.wsmLogout"/>
  <testcase name="TC03_ErrorMessage" time="1.775" classname="WSM_LOGOUT.wsmLogout"/>
  <testcase name="TC04_LogoutAtAnyPage" time="34.684" classname="WSM_LOGOUT.wsmLogout"/>
  <testcase name="TC05_NavigateAfterLogout" time="1.184" classname="WSM_LOGOUT.wsmLogout">
    <failure type="java.lang.AssertionError" message="expected [https://wsm.framgia.vn/en] but found [https://wsm.framgia.vn/en/dashboard/user_settings/edit]">
      <![CDATA[java.lang.AssertionError: expected [https://wsm.framgia.vn/en] but found [https://wsm.framgia.vn/en/dashboard/user_settings/edit]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at WSM_LOGOUT.wsmLogout.TC05_NavigateAfterLogout(wsmLogout.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC05_NavigateAfterLogout -->
</testsuite> <!-- Default test -->
